export const FILE_DOWNLOAD_REQUEST = "FILE_DOWNLOAD_REQUEST";
export const FILE_DOWNLOAD_SUCCESS = "FILE_DOWNLOAD_SUCCESS";
export const FILE_DOWNLOAD_FAIL = "FILE_DOWNLOAD_FAIL";
export const FILE_DOWNLOAD_RESET = "FILE_DOWNLOAD_RESET";

export const FILE_CREATE_REQUEST = "FILE_CREATE_REQUEST";
export const FILE_CREATE_SUCCESS = "FILE_CREATE_SUCCESS";
export const FILE_CREATE_FAIL = "FILE_CREATE_FAIL";
